
swaync_config_file="/home/tohru/.config/swaync/config.json"
swaync_css_widgets="/home/tohru/.config/swaync/widgets.css"
swaync_reload_command="swaync-client --reload-css && swaync-client --reload-config"

css_prepend="@define-color pink rgb(245, 194, 231); @define-color crust rgb(17, 17, 27); @define-color surface0 #313244; @define-color text rgb(205, 214, 244);\n"
css_button_selector=".widget-buttons-grid>flowbox>flowboxchild:nth-child(?)>button"
css_button_hover_selector=".widget-buttons-grid>flowbox>flowboxchild:nth-child(?)>button:hover"
css_label_selector=".widget-buttons-grid>flowbox>flowboxchild:nth-child(?)>button>label"
css_label_hover_selector=".widget-buttons-grid>flowbox>flowboxchild:nth-child(?)>button:hover>label"

[styles_on]
css_button="background: @pink; border: 2px solid @pink"
css_button_hover="background: @pink; border: 2px solid @pink"
css_label="color: @crust;"
css_label_hover="color: @crust;"

[styles_off]
css_button="background: @transparent; border: 2px solid @surface0"
css_button_hover="background: @transparent; border: 2px solid @pink"
css_label="color: @text;"
css_label_hover="color: @pink;"

# widgets
[vpn]
desc="vpn"
index="4"
off_label="  VPN"
on_label="  Connected"
turn_on_command="nmcli con up id user1"
turn_off_command="nmcli con down id user1"
check_status_command="nmcli con show --active | grep -i 'vpn'"

[mute]
desc="mute"
index="2"
off_label="󰕾  Mute"
on_label="󰕾  Muted"
turn_on_command="pactl set-sink-mute @DEFAULT_SINK@ on"
turn_off_command="pactl set-sink-mute @DEFAULT_SINK@ off"
check_status_command="pactl get-sink-mute @DEFAULT_SINK@ | grep \"yes\""

[wifi]
desc="wifi"
index="1"
off_label="󱚼   Wi-FI"
on_label="   Connected"
turn_on_command="nmcli con up id RedHot_5G"
turn_off_command="nmcli con down id RedHot_5G"
check_status_command="nmcli con show --active | grep -i 'wifi'"


[bluetooth]
desc="bluetooth"
index="3"
off_label="󰂲  Bluetooth"
on_label="󰂯  Bluetooth"
turn_on_command="rfkill unblock bluetooth"
turn_off_command="rfkill block bluetooth"
check_status_command="rfkill list bluetooth | grep \"Soft blocked: no\""
